![logo_ironhack_blue 7](https://user-images.githubusercontent.com/23629340/40541063-a07a0a8a-601a-11e8-91b5-2f13e4e6b441.png)

# LAB | Connecting Python to SQL

<details>
  <summary>
   <h2>Learning Goals</h2>
  </summary>

  This lab allows you to practice and apply the concepts and techniques taught in class. 

  Upon completion of this lab, you will be able to:
  
- Write a Python script to connect to a relational database using the appropriate Python library and query it using SQL commands.

  <br>
  <hr> 

</details>

<details>
  <summary>
   <h2>Prerequisites</h2>
  </summary>

Before this starting this lab, you should have learnt about:

- Basic SQL queries
- Python and Pandas 
- Data Wrangling, which involves tasks such as grouping, aggregating, dealing with indexes, renaming columns, merging data and performing calculations.
 
  <br>
  <hr> 

</details>


## Introduction

Welcome to the Connecting Python to SQL lab!

In this lab, you will be working with the [Sakila](https://dev.mysql.com/doc/sakila/en/) database on movie rentals. Specifically, you will be practicing how to do basic SQL queries using Python. By connecting Python to SQL, you can leverage the power of both languages to efficiently manipulate and analyze large datasets. Throughout this lab, you will practice how to use Python to retrieve and manipulate data stored in the Sakila database using SQL queries. Let's get started!

## Challenge

In this lab, the objective is to identify the customers who were active in both May and June, and how did their activity differ between months. To achieve this, follow these steps:

1. Establish a connection between Python and the Sakila database.

2. Write a Python function called `rentals_month` that retrieves rental data for a given month and year (passed as parameters) from the Sakila database as a Pandas DataFrame. The function should take in three parameters:

	- `engine`: an object representing the database connection engine to be used to establish a connection to the Sakila database.
	- `month`: an integer representing the month for which rental data is to be retrieved.
	- `year`: an integer representing the year for which rental data is to be retrieved.

	The function should execute a SQL query to retrieve the rental data for the specified month and year from the rental table in the Sakila database, and return it as a pandas DataFrame.

3. Develop a Python function called `rental_count_month` that takes the DataFrame provided by `rentals_month` as input along with the month and year and returns a new DataFrame containing the number of rentals made by each customer_id during the selected month and year. 

	The function should also include the month and year as parameters and use them to name the new column according to the month and year, for example, if the input month is 05 and the year is 2005, the column name should be "rentals_05_2005".


	*Hint: Consider making use of pandas [groupby()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html)*

4. Create a Python function called `compare_rentals` that takes two DataFrames as input containing the number of rentals made by each customer in different months and years. 
The function should return a combined DataFrame with a new 'difference' column, which is the difference between the number of rentals in the two months.

## Requirements

- Fork this repo
- Clone it to your machine



## Getting Started

Complete the challenges. Follow the instructions and add your code and explanations as necessary.

## Submission

- Upon completion, run the following commands:

```bash
git add .
git commit -m "Solved lab"
git push origin master
```

- Paste the link of your lab in Student Portal.

---
---
# Solved Lab | Connecting Python to SQL
---


## Solved Challenge

In this lab, the objective is to identify the customers who were active in both May and June, and how did their activity differ between months. To achieve this, follow these steps:

### 1. Establish a connection between Python and the Sakila database.

In [9]:
# install sqlalchemy pymysql to connect to mysql database
!pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in c:\users\sboub\appdata\local\programs\python\python310\lib\site-packages (2.0.48)
Requirement already satisfied: pymysql in c:\users\sboub\appdata\local\programs\python\python310\lib\site-packages (1.1.2)
Requirement already satisfied: greenlet>=1 in c:\users\sboub\appdata\local\programs\python\python310\lib\site-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\sboub\appdata\roaming\python\python310\site-packages (from sqlalchemy) (4.15.0)

In [32]:
from sqlalchemy import create_engine
import pandas as pd

# Update with your credentials
user = "root"
password = "your_password"
host = "localhost"
port = 3306
database = "sakila"

# engine = create_engine(f"mysql+pymysql://{user}:{password}@{host}:{port}/{database}")


sakila_engine = create_engine("mysql+pymysql://root:ironhack13@localhost:3306/sakila")

In [38]:
import pandas as pd
pd.set_option('display.max_rows', None) # Show the full table in Jupyter
engine = sakila_engine
# Test the connection by running a simple query

# to fetch the first 5 rows of the customer table
df_customer = pd.read_sql("SELECT * FROM customer LIMIT 5;", engine)  
display(df_customer.head())


# to fetch all rows of the customer table
df_customer = pd.read_sql("SELECT * FROM `customer`;", engine) 
# to fetch all rows of the customer table
df_customer = pd.read_sql("SELECT * FROM `customer`;", engine) 

# -----------------------------
# Fetch all tables in the database
# -----------------------------
tables = pd.read_sql("SHOW TABLES;", engine)
display(tables)

tables = tables.iloc[:, 0].tolist()  # Extract table names from the DataFrame

for table in tables:
    df = pd.read_sql(f"SELECT * FROM {table};", engine)
    display(df.head())

,customer_id,store_id,first_name,last_name,email,address_id,active,create_date,last_update
0,1,1,MARY,SMITH,MARY.SMITH@sakilacustomer.org,5,1,2006-02-14 22:04:36,2006-02-15 04:57:20
1,2,1,PATRICIA,JOHNSON,PATRICIA.JOHNSON@sakilacustomer.org,6,1,2006-02-14 22:04:36,2006-02-15 04:57:20
2,3,1,LINDA,WILLIAMS,LINDA.WILLIAMS@sakilacustomer.org,7,1,2006-02-14 22:04:36,2006-02-15 04:57:20
3,4,2,BARBARA,JONES,BARBARA.JONES@sakilacustomer.org,8,1,2006-02-14 22:04:36,2006-02-15 04:57:20
4,5,1,ELIZABETH,BROWN,ELIZABETH.BROWN@sakilacustomer.org,9,1,2006-02-14 22:04:36,2006-02-15 04:57:20

              Tables_in_sakila
0                        actor
1                   actor_info
2                      address
3                     category
4                         city
5                      country
6                     customer
7                customer_list
8      customer_rental_summary
9                         film
10                  film_actor
11               film_category
12                   film_list
13                   film_text
14                   inventory
15                    language
16  nicer_but_slower_film_list
17                     payment
18                      rental
19      sales_by_film_category
20              sales_by_store
21                       staff
22                  staff_list
23                       store

   actor_id first_name     last_name         last_update
0         1   PENELOPE       GUINESS 2006-02-15 04:34:33
1         2       NICK      WAHLBERG 2006-02-15 04:34:33
2         3         ED         CHASE 2006-02-15 04:34:33
3         4   JENNIFER         DAVIS 2006-02-15 04:34:33
4         5     JOHNNY  LOLLOBRIGIDA 2006-02-15 04:34:33

,actor_id,first_name,last_name,film_info
0,1,PENELOPE,GUINESS,Animation: ANACONDA CONFESSIONS; Children: LAN...
1,2,NICK,WAHLBERG,Action: BULL SHAWSHANK; Animation: FIGHT JAWBR...
2,3,ED,CHASE,"Action: CADDYSHACK JEDI, FORREST SONS; Classic..."
3,4,JENNIFER,DAVIS,Action: BAREFOOT MANCHURIAN; Animation: ANACON...
4,5,JOHNNY,LOLLOBRIGIDA,"Action: AMADEUS HOLY, GRAIL FRANKENSTEIN, RING..."

,address_id,address,address2,district,city_id,postal_code,phone,location,last_update
0,1,47 MySakila Drive,None,Alberta,300,,,b'\x00\x00\x00\x00\x01\x01\x00\x00\x00>\n2]c4\...,2014-09-25 22:30:27
1,2,28 MySQL Boulevard,None,QLD,576,,,b'\x00\x00\x00\x00\x01\x01\x00\x00\x00\x8e\x10...,2014-09-25 22:30:09
2,3,23 Workhaven Lane,None,Alberta,300,,14033335568,b'\x00\x00\x00\x00\x01\x01\x00\x00\x00\xcd\xc4...,2014-09-25 22:30:27
3,4,1411 Lillydale Drive,None,QLD,576,,6172235589,b'\x00\x00\x00\x00\x01\x01\x00\x00\x00[\r\xe44...,2014-09-25 22:30:09
4,5,1913 Hanoi Way,,Nagasaki,463,35200,28303384290,b'\x00\x00\x00\x00\x01\x01\x00\x00\x00(\xd17\x...,2014-09-25 22:31:53

   category_id       name         last_update
0            1     Action 2006-02-15 04:46:27
1            2  Animation 2006-02-15 04:46:27
2            3   Children 2006-02-15 04:46:27
3            4   Classics 2006-02-15 04:46:27
4            5     Comedy 2006-02-15 04:46:27

   city_id                  city  country_id         last_update
0        1  A Coruña (La Coruña)          87 2006-02-15 04:45:25
1        2                  Abha          82 2006-02-15 04:45:25
2        3             Abu Dhabi         101 2006-02-15 04:45:25
3        4                 Acuña          60 2006-02-15 04:45:25
4        5                 Adana          97 2006-02-15 04:45:25

   country_id         country         last_update
0           1     Afghanistan 2006-02-15 04:44:00
1           2         Algeria 2006-02-15 04:44:00
2           3  American Samoa 2006-02-15 04:44:00
3           4          Angola 2006-02-15 04:44:00
4           5        Anguilla 2006-02-15 04:44:00

,customer_id,store_id,first_name,last_name,email,address_id,active,create_date,last_update
0,1,1,MARY,SMITH,MARY.SMITH@sakilacustomer.org,5,1,2006-02-14 22:04:36,2006-02-15 04:57:20
1,2,1,PATRICIA,JOHNSON,PATRICIA.JOHNSON@sakilacustomer.org,6,1,2006-02-14 22:04:36,2006-02-15 04:57:20
2,3,1,LINDA,WILLIAMS,LINDA.WILLIAMS@sakilacustomer.org,7,1,2006-02-14 22:04:36,2006-02-15 04:57:20
3,4,2,BARBARA,JONES,BARBARA.JONES@sakilacustomer.org,8,1,2006-02-14 22:04:36,2006-02-15 04:57:20
4,5,1,ELIZABETH,BROWN,ELIZABETH.BROWN@sakilacustomer.org,9,1,2006-02-14 22:04:36,2006-02-15 04:57:20

,ID,name,address,zip code,phone,city,country,notes,SID
0,218,VERA MCCOY,1168 Najafabad Parkway,40301,886649065861,Kabul,Afghanistan,active,1
1,441,MARIO CHEATHAM,1924 Shimonoseki Drive,52625,406784385440,Batna,Algeria,active,1
2,69,JUDY GRAY,1031 Daugavpils Parkway,59025,107137400143,Béchar,Algeria,active,2
3,176,JUNE CARROLL,757 Rustenburg Avenue,89668,506134035434,Skikda,Algeria,active,1
4,320,ANTHONY SCHWAB,1892 Nabereznyje Tšelny Lane,28396,478229987054,Tafuna,American Samoa,active,2

,customer_id,first_name,last_name,email,rental_count
0,1,MARY,SMITH,MARY.SMITH@sakilacustomer.org,32
1,2,PATRICIA,JOHNSON,PATRICIA.JOHNSON@sakilacustomer.org,27
2,3,LINDA,WILLIAMS,LINDA.WILLIAMS@sakilacustomer.org,26
3,4,BARBARA,JONES,BARBARA.JONES@sakilacustomer.org,22
4,5,ELIZABETH,BROWN,ELIZABETH.BROWN@sakilacustomer.org,38

,film_id,title,description,release_year,language_id,original_language_id,rental_duration,rental_rate,length,replacement_cost,rating,special_features,last_update
0,1,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,2006,1,None,6,0.99,86,20.99,PG,"Deleted Scenes,Behind the Scenes",2006-02-15 05:03:42
1,2,ACE GOLDFINGER,A Astounding Epistle of a Database Administrat...,2006,1,None,3,4.99,48,12.99,G,"Trailers,Deleted Scenes",2006-02-15 05:03:42
2,3,ADAPTATION HOLES,A Astounding Reflection of a Lumberjack And a ...,2006,1,None,7,2.99,50,18.99,NC-17,"Trailers,Deleted Scenes",2006-02-15 05:03:42
3,4,AFFAIR PREJUDICE,A Fanciful Documentary of a Frisbee And a Lumb...,2006,1,None,5,2.99,117,26.99,G,"Commentaries,Behind the Scenes",2006-02-15 05:03:42
4,5,AFRICAN EGG,A Fast-Paced Documentary of a Pastry Chef And ...,2006,1,None,6,2.99,130,22.99,G,Deleted Scenes,2006-02-15 05:03:42

   actor_id  film_id         last_update
0         1        1 2006-02-15 05:05:03
1         1       23 2006-02-15 05:05:03
2         1       25 2006-02-15 05:05:03
3         1      106 2006-02-15 05:05:03
4         1      140 2006-02-15 05:05:03

   film_id  category_id         last_update
0        1            6 2006-02-15 05:07:09
1        2           11 2006-02-15 05:07:09
2        3            6 2006-02-15 05:07:09
3        4           11 2006-02-15 05:07:09
4        5            8 2006-02-15 05:07:09

,FID,title,description,category,price,length,rating,actors
0,1,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,Documentary,0.99,86,PG,"PENELOPE GUINESS, CHRISTIAN GABLE, LUCILLE TRA..."
1,2,ACE GOLDFINGER,A Astounding Epistle of a Database Administrat...,Horror,4.99,48,G,"BOB FAWCETT, MINNIE ZELLWEGER, SEAN GUINESS, C..."
2,3,ADAPTATION HOLES,A Astounding Reflection of a Lumberjack And a ...,Documentary,2.99,50,NC-17,"NICK WAHLBERG, BOB FAWCETT, CAMERON STREEP, RA..."
3,4,AFFAIR PREJUDICE,A Fanciful Documentary of a Frisbee And a Lumb...,Horror,2.99,117,G,"JODIE DEGENERES, SCARLETT DAMON, KENNETH PESCI..."
4,5,AFRICAN EGG,A Fast-Paced Documentary of a Pastry Chef And ...,Family,2.99,130,G,"GARY PHOENIX, DUSTIN TAUTOU, MATTHEW LEIGH, MA..."

,film_id,title,description
0,1,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...
1,2,ACE GOLDFINGER,A Astounding Epistle of a Database Administrat...
2,3,ADAPTATION HOLES,A Astounding Reflection of a Lumberjack And a ...
3,4,AFFAIR PREJUDICE,A Fanciful Documentary of a Frisbee And a Lumb...
4,5,AFRICAN EGG,A Fast-Paced Documentary of a Pastry Chef And ...

   inventory_id  film_id  store_id         last_update
0             1        1         1 2006-02-15 05:09:17
1             2        1         1 2006-02-15 05:09:17
2             3        1         1 2006-02-15 05:09:17
3             4        1         1 2006-02-15 05:09:17
4             5        1         2 2006-02-15 05:09:17

   language_id      name         last_update
0            1   English 2006-02-15 05:02:19
1            2   Italian 2006-02-15 05:02:19
2            3  Japanese 2006-02-15 05:02:19
3            4  Mandarin 2006-02-15 05:02:19
4            5    French 2006-02-15 05:02:19

,FID,title,description,category,price,length,rating,actors
0,1,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,Documentary,0.99,86,PG,"Penelope Guiness, Christian Gable, Lucille Tra..."
1,2,ACE GOLDFINGER,A Astounding Epistle of a Database Administrat...,Horror,4.99,48,G,"Bob Fawcett, Minnie Zellweger, Sean Guiness, C..."
2,3,ADAPTATION HOLES,A Astounding Reflection of a Lumberjack And a ...,Documentary,2.99,50,NC-17,"Nick Wahlberg, Bob Fawcett, Cameron Streep, Ra..."
3,4,AFFAIR PREJUDICE,A Fanciful Documentary of a Frisbee And a Lumb...,Horror,2.99,117,G,"Jodie Degeneres, Scarlett Damon, Kenneth Pesci..."
4,5,AFRICAN EGG,A Fast-Paced Documentary of a Pastry Chef And ...,Family,2.99,130,G,"Gary Phoenix, Dustin Tautou, Matthew Leigh, Ma..."

,payment_id,customer_id,staff_id,rental_id,amount,payment_date,last_update
0,1,1,1,76,2.99,2005-05-25 11:30:37,2006-02-15 22:12:30
1,2,1,1,573,0.99,2005-05-28 10:35:23,2006-02-15 22:12:30
2,3,1,1,1185,5.99,2005-06-15 00:54:12,2006-02-15 22:12:30
3,4,1,2,1422,0.99,2005-06-15 18:02:53,2006-02-15 22:12:30
4,5,1,2,1476,9.99,2005-06-15 21:08:46,2006-02-15 22:12:30

,rental_id,rental_date,inventory_id,customer_id,return_date,staff_id,last_update
0,1,2005-05-24 22:53:30,367,130,2005-05-26 22:04:30,1,2006-02-15 21:30:53
1,2,2005-05-24 22:54:33,1525,459,2005-05-28 19:40:33,1,2006-02-15 21:30:53
2,3,2005-05-24 23:03:39,1711,408,2005-06-01 22:12:39,1,2006-02-15 21:30:53
3,4,2005-05-24 23:04:41,2452,333,2005-06-03 01:43:41,2,2006-02-15 21:30:53
4,5,2005-05-24 23:05:21,2079,222,2005-06-02 04:33:21,1,2006-02-15 21:30:53

    category  total_sales
0     Sports      5314.21
1     Sci-Fi      4756.98
2  Animation      4656.30
3      Drama      4587.39
4     Comedy      4383.58

                 store       manager  total_sales
0  Woodridge,Australia  Jon Stephens     33726.77
1    Lethbridge,Canada  Mike Hillyer     33679.79

,staff_id,first_name,last_name,address_id,picture,email,store_id,active,username,password,last_update
0,1,Mike,Hillyer,3,b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\...,Mike.Hillyer@sakilastaff.com,1,1,Mike,8cb2237d0679ca88db6464eac60da96345513964,2006-02-15 03:57:16
1,2,Jon,Stephens,4,None,Jon.Stephens@sakilastaff.com,2,1,Jon,None,2006-02-15 03:57:16

,ID,name,address,zip code,phone,city,country,SID
0,1,Mike Hillyer,23 Workhaven Lane,,14033335568,Lethbridge,Canada,1
1,2,Jon Stephens,1411 Lillydale Drive,,6172235589,Woodridge,Australia,2

   store_id  manager_staff_id  address_id         last_update
0         1                 1           1 2006-02-15 04:57:12
1         2                 2           2 2006-02-15 04:57:12

In [34]:
df_customer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 599 entries, 0 to 598
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  599 non-null    int64
 1   store_id     599 non-null    int64
 2   first_name   599 non-null    object
 3   last_name    599 non-null    object
 4   email        599 non-null    object
 5   address_id   599 non-null    int64
 6   active       599 non-null    int64
 7   create_date  599 non-null    datetime64[ns]
 8   last_update  599 non-null    datetime64[ns]
dtypes: datetime64[ns](2), int64(4), object(3)
memory usage: 42.2+ KB

### 2. Write a Python function called `rentals_month`

This function retrieves rental data for a given month and year (passed as parameters) from the Sakila database as a Pandas DataFrame. The function should take in three parameters:
- `engine`: an object representing the database connection engine to be used to establish a connection to the Sakila database.
- `month`: an integer representing the month for which rental data is to be retrieved.
- `year`: an integer representing the year for which rental data is to be retrieved.

The function should execute a SQL query to retrieve the rental data for the specified month and year from the rental table in the Sakila database, and return it as a pandas DataFrame.

In [35]:
import pandas as pd

def rentals_month(month, year, engine=sakila_engine):
    """
    Retrieve rental data for a given month and year from the Sakila database.

    Parameters:
    - engine: SQLAlchemy engine connected to the Sakila database
    - month: int, month number (1-12)
    - year: int, year (e.g., 2005)
    
    Returns:
    - pandas DataFrame with customer_id and rental_date for the specified month/year
    """
    # SQL query to select rentals in the specified month and year
    query = f"""
        SELECT customer_id, rental_date
        FROM rental
        WHERE MONTH(rental_date) = {month} 
          AND YEAR(rental_date) = {year};
    """
    
    # Execute the query and return a DataFrame
    df_rentals_month = pd.read_sql(query, engine)
    return df_rentals_month

# test the function for January 2005
df_jan_2005 = rentals_month(1, 2005, engine=sakila_engine)
display(df_jan_2005.head())

Empty DataFrame
Columns: [customer_id, rental_date]
Index: []

### 3. Develop a Python function called `rental_count_month` 

This function takes the DataFrame provided by `rentals_month` as input along with the month and year and returns a new DataFrame containing the number of rentals made by each customer_id during the selected month and year. 

The function should also include the month and year as parameters and use them to name the new column according to the month and year, for example, if the input month is 05 and the year is 2005, the column name should be "rentals_05_2005".


*Hint: Consider making use of pandas [groupby()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html)*

In [30]:
import pandas as pd

def rental_count_month(df, month, year):
    column_name = f"rentals_{month:02d}_{year}"
    
    result = (
        df.groupby("customer_id")
          .size()
          .reset_index(name=column_name)
    )
    
    return result

# test the function for January 2005
df_jan_2005_count = rental_count_month(df_jan_2005, 1, 2005)
display(df_jan_2005_count.head())

Empty DataFrame
Columns: [customer_id, rentals_01_2005]
Index: []

### 4. Create a Python function called `compare_rentals` 

This function takes two DataFrames as input containing the number of rentals made by each customer in different months and years. 

The function should return a combined DataFrame with a new 'difference' column, which is the difference between the number of rentals in the two months.

In [31]:
import pandas as pd

def compare_rentals(df1, df2):
    merged = pd.merge(df1, df2, on="customer_id", how="outer").fillna(0)
    
    # Identify rental columns
    col1 = df1.columns[1]
    col2 = df2.columns[1]
    
    merged["difference"] = merged[col2] - merged[col1]
    
    return merged

# test the function by comparing January 2005 and February 2005